### ISSUE TITLE
Implement wallet features in Web3Signer

### ISSUE THREAD

**Issue by dakingha69** [trustlines-protocol/clientlib#122]
### Problem
Web3Signer currently only supports `confirm` and `getTxInfos`. Keystore / Wallet related methods were not implemented yet. 

### Solution
Implement wallet related methods in Web3Signer using web3:

### Tasks
- [ ] createAccount
- [ ] loadAccount
- [ ] signMsgHash
- [ ] getBalance
- [ ] encrypt
- [ ] decrypt
- [ ] showSeed
- [ ] recoverFromSeed
- [ ] exportPrivateKey

**Comment by andfletcher** [comment]
Outdated
