### ISSUE TITLE
Release new version 0.4.0

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/clientlib#217]
Release the new version 0.4.0. This includes writing the changlog, and please highlight the breaking changes with the help of @cducrest .
I know that there where some.

**Comment by dakingha69** [comment]
Just talked with come and there are no breaking changes. Would you still use the version 0.4.0? Or just 0.3.1?

**Comment by schmir** [comment]
We haven't put out a release AFAICT. Therefore I'm reopening it.

**Comment by schmir** [comment]
0.4.0 has been released on npmjs: https://www.npmjs.com/package/trustlines-clientlib
