### ISSUE TITLE
Add extraData to transfers

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/clientlib#232]
In `Paymnet.ts`, we need to add the option for user to specify `extraData` on preparing a TL payment.

We should also add this to `getPath` since it returns the gas estimation for the transaction using this path and this should depend on the (size of) extraData even though it feels odd.
See: https://github.com/trustlines-protocol/relay/blob/d2b44ac488341b4d7ebfaffd4f5d9c905da07b5c/docs/RelayAPI.md#transfer-path-in-currency-network

**Comment by berndbohmeier** [comment]
Maybe we can improve on the naming of `getPath`
