### ISSUE TITLE
Why is trustlines-contracts-abi set to "dev"?

### ISSUE THREAD

**Issue by compojoom** [trustlines-protocol/clientlib#249]
the dependency on trustlines-contracts-abi is specified as "dev". 

I couldn't find the yarn docs on how it resolves "dev" dependencies, but here is my guess what happens. 

Dev is treated as a version number. So when we install the clientlib for the first time - it asks for the latest version of contracts-abi from npm and stores that under
trustlines-contracts-abi@dev:

in yarn.lock. 

At one point of time the clientlib might require a higher number from contracts-abi. But since we've specified "dev" yarn won't automatically update it. To actually fetch a new version for contracts-abi we have to delete the trustlines-contracts-abi@dev from yarn.lock.

I think that we should specify which version of the trustlines-contracts-abi the clientlib depends on.

**Comment by berndbohmeier** [comment]
Solved.
