### ISSUE TITLE
Add delegation fees and network of fees as tx options for meta transactions

### ISSUE THREAD

**Issue by dakingha69** [trustlines-protocol/clientlib#253]
When executing a normal transaction we are able to pass in optional `gasPrice` and `gasLimit` parameters in `TxOptions` when preparing it, e.g. https://github.com/trustlines-protocol/clientlib/blob/master/src/Transaction.ts#L53-L54. Those values are then used to return the transaction costs in `ethFees`.
Currently we do the same for meta transactions which is misleading because in this context the parameters `gasPrice` and `gasLimit` are not needed. Instead we need `delegationFees` and `networkOfFees` as  additional optional parameters. If not set by the user those should also default to values returned by the relay server. Instead of `ethFees` the `delegationFees` and `networkOfFees` should also be returned.

**Comment by cducrest** [comment]
done.
