### ISSUE TITLE
Refactor getDelegationFees

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/clientlib#271]
This is a follow up of https://github.com/trustlines-protocol/clientlib/pull/269/files to make the function getDelegationFees better (https://github.com/trustlines-protocol/clientlib/pull/269/files#diff-1e657e773ebb13137b9281cc47cdd8efR148)
It takes delegationFees as option only to return them, which is unintuitive.

**Comment by cducrest** [comment]
We defer this to a bigger refactoring of the clientlib.
