### ISSUE TITLE
Add function to get list of all trustlines a user has in all networks

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/clientlib#295]
We've already added a new endpoint to the relay server: https://github.com/trustlines-protocol/relay/blob/master/docs/RelayAPI.md#all-trustlines-of-user-in-all-currency-networks

This needs to be made accessible via the clientlib.

/cc @nekhaly

**Comment by andfletcher** [comment]
@schmir was this not done in this issue https://github.com/trustlines-protocol/clientlib/pull/298 ?

**Comment by andfletcher** [comment]
Done
