### ISSUE TITLE
Delegation fee should return a value one can use

### ISSUE THREAD

**Issue by compojoom** [trustlines-protocol/clientlib#317]
Currently the prepare payment function returns a delegationfee object:
https://github.com/trustlines-protocol/clientlib/blob/master/src/Payment.ts#L123

Users of the library need to then manually calculate the delegation fee. It would help a lot of we get a value that we can directly use.

**Comment by berndbohmeier** [comment]
Should be fixed in the next release, we now have:
```
{txFees, rawtx} = prepareXX()
fees = txFees.totalFees.value
```
