### ISSUE TITLE
Fix network fee calculation

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/clientlib#320]
Andreas pointed out that if you do a payment of `1` with a fee of `0.1` %, instead of returning a fee of `0.001` the lib returns `0.00100101`. Also it turns out that the `raw` value is also wrong, so it does not seem to be the conversion of raw to value.
We most likely do a calculation without using bignumber somewhere.

**Comment by cducrest** [comment]
It's not a bug, it's a
# FEATURE
https://github.com/trustlines-network/project/wiki/Capacity-Imbalance-Fee-Specification: `fee = (imbalance_generated - 1) / (d - 1) + 1`
He sends 1 with 8 decimals and an imbalance fee of `0.1%` so `fee = (100000000-1)/(1000-1) + 1 = 100101`
