### ISSUE TITLE
Add query parameters to generated links

### ISSUE THREAD

**Issue by compojoom** [trustlines-protocol/clientlib#336]
Currently the clientlib generates URLs that have a predefined structure, but one is not able to add any additional query parameters to those links. 

Moreover the generated payment link is hard to work with as it can change it's path depending on whether one has provided a subject or not:
https://github.com/trustlines-protocol/clientlib/blob/master/src/Payment.ts#L263

We generate links in Payment, User and Contact. The createLink function in those classes is a proxy to utils.createLink, which calls utils.buildURL. 

I think that we should modify the buildUrl function and add a third param to it "queryParams". If the user needs additional params to the URL he could provide those as an array/object and the clientlib would create the correct link.

For example the Payment link could look like this
/:newtorkAddress/:userAddress/:amount?param1=1&param2=2 etc

The subject for a payment url should also be attached as a query param.

I don't think we can implement this as a non-breaking change as this would basically modify the signature of the functions… And in the case of createRequest I would actually change it from:

```
  public async createRequest(
    networkAddress: string,
    amount: number,
    subject: string,
    customBase?: string
  ): Promise<string> {
```
to

```
  public async createRequest(
    networkAddress: string,
    amount: number,
    queryParams: array|object,
    customBase?: string
  ): Promise<string> {
```

if this change is ok for you guys I could create a PR for this.

**Comment by compojoom** [comment]
Actually it seems that if params is an array - we create a path url.

If params is an object we add the params as query params.

This seems confusing for me.

I would change the function definition to
```
export const buildUrl = (baseUrl: string, pathParams?: array, queryParams?: object): string => {

}
```

With such a definition I think that it would be clear what the expected result of the function would be.

**Comment by berndbohmeier** [comment]
The way forward here is I will look at what links we create and how exactly they should look and then sync with Daniel if that is fine.
