### ISSUE TITLE
Add message parameter to prepare payment function

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/clientlib#348]
Add the message parameter. If it is set it should later when confirming the transaction also send a TransferMessage via the messaging service. 
It also needs to encode a transfer id in the extraData. This can for now use a dummy implementation, but should later used the same format we will agree on for the payment request id. 

Depends on https://github.com/trustlines-protocol/clientlib/issues/346

**Comment by cducrest** [comment]
We updated the requirements after discussing with the app team. The function to prepare the payment will include a `messageId` in the prepared payment, but the message will be provided upon confirmation of the payment.
