### ISSUE TITLE
Check randomness of random nonce

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/clientlib#374]
Check if we get the same nonce twice with a high probability / when restarting the app / when sending too fast.
Check how the random generator is initialised.

**Comment by berndbohmeier** [comment]
The clientlib tries to use cryptographic secure numbers and print a warning if that is not possible.
if not using cryptographic secure numbers it uses `math.random()` which is I guess the best we can do.

So the thing left to check is if the range of 0 to 10*19 ~ 63 bit is enough.

**Comment by berndbohmeier** [comment]
With the approximation of the birthday problem (see https://en.wikipedia.org/wiki/Birthday_problem#The_generalized_birthday_problem)
```
p(n) = n**2/(2m)
```

The probability for a person sending 10 years a transaction every second `(10*365*24*60*60)`
Is then `0.4%` when using 10*19. This is fine for normal usage, but we should increase the number if blockchain scale and people send a lot of transfers. 
With `10**15` for payment request `p(n)` is already `50%` so we should also increase it to 10**19 there.

**Comment by cducrest** [comment]
Done.
